# Generated by Django 2.2 on 2019-07-21 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AddField(
            model_name='post',
            name='bad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='good',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=128),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
