# Generated by Django 2.2 on 2019-07-21 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20190721_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_time',
            field=models.CharField(max_length=256),
        ),
    ]
